### ISSUE TITLE
Replace 0% APR with Pending

### ISSUE THREAD

**Issue by vfat0** [hundred-finance/hundred-dao-ui#4]
Currently if the APR has not been set for the next week, it shows as 0% which is misleading (it won't be 0%, it just hasn't been decided yet).

A better option for this would be to show e.g. `30% -> Pending` instead of `30% -> 0%`

**Comment by SHA-2048** [comment]
thank you @jbeanz for helping with this task 🙏

**Comment by jbeanz** [comment]
> thank you @jbeanz for helping with this task 🙏

;-) no problemo
