### ISSUE TITLE
Add prettier configs

### ISSUE THREAD

**Issue by SHA-2048** [hundred-finance/hundred-dao-ui#6]
The code style is far from being clean. A first step to make it better would be to standardise it using prettier.
We need to add following config files

`.prettierrc`
`.prettierignore`

a simple style example could be
```
{
    "singleQuote": true,
    "arrowParens": "avoid",
    "trailingComma": "none",
    "tabWidth": 4,
    "svelteSortOrder": "options-scripts-styles-markup"
}
```

**Comment by jbeanz** [comment]
ok working on it :)

**Comment by SHA-2048** [comment]
good job @jbeanz
