### ISSUE TITLE
Correct estimated liquidity to add at max boost

### ISSUE THREAD

**Issue by SHA-2048** [hundred-finance/hundred-dao-ui#7]
when hovering over the user liquidity figures we see this

![image](https://user-images.githubusercontent.com/8516712/152114568-21ed0fa4-21f9-4949-bc2e-6ba45907c173.png)

This figure is currently calculated using the applied boost, which can be incorrect if the effective boost value is different. In fact if the user interacts with the voting contract, the boost will get updated, and so in that sense, the estimated figure user saw was misleading

The value is calculated here: https://github.com/hundred-finance/hundred-dao-ui/blob/92489ce7ced3b9cb2746a917117f65f616cfb61d/stores/gaugeStore.js#L899

**Comment by Aman-Mandal** [comment]
Hello , I am very new in Open Source and I wanna take this issue..  but can you guide me what I have to do exactly . Thankyouu :)

**Comment by SHA-2048** [comment]
> Hello , I am very new in Open Source and I wanna take this issue.. but can you guide me what I have to do exactly . Thankyouu :)

the code to correct is linked in the description. But of course you need to read the overall code a bit and understand the relations between components
